default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: thants
  host: postgres

development:
  <<: *default
  database: minio_test_development

test:
  <<: *default
  database: minio_test_test

production:
  <<: *default
  database: minio_test_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
