version: "3"
x-rails-base: &rails_base
  build: ./
  environment:
    NODE_ENV: development
    RAILS_ENV: development
    RACK_ENV: development
    RAILS_LOG_TO_STDOUT: "true"
  volumes:
    - ./:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
  links:
    - postgres
  depends_on:
    - postgres
  tty: true
  stdin_open: true

services:
  app:
    <<: *rails_base
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    ports:
      - 8001:3000

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thants
      TZ: Asia/Tokyo
    volumes:
      - "db-data:/var/lib/postgresql/data"
  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret

volumes:
  bundle:
  node_modules:
  db-data:
  minio:
    driver: local
